apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aggregator-chart.fullname" . }}
  labels:
    {{- include "aggregator-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aggregator-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aggregator-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aggregator-chart.serviceAccountName" . }}
      automountServiceAccountToken: true
      volumes:
        - name: {{ include "aggregator-chart.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "aggregator-chart.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AGGREGATOR_MACHINE_ID
              value: {{ .Values.machine_id | default uuidv4 }}
            - name: PROJECT_TOKEN
              value: {{ required "A valid Calyptia project_token is required!" .Values.project_token }}
            - name: AGGREGATOR_STORE_PATH
              value: /opt/calyptia-aggregator/.store/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/calyptia-aggregator/
              name: {{ include "aggregator-chart.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
